# -*- coding: utf-8 -*-
"""raspagem_CNH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WWDnZbNB4JqD2nSvBheuEVOmmPe6-Sh
"""

"""
Raspagem de comentários do YouTube — Mudanças no processo de CNH no Brasil
===========================================================================
Utiliza a YouTube Data API v3 (gratuita, até 10.000 unidades/dia).

COMO USAR:
1. Obtenha uma API Key gratuita em: https://console.cloud.google.com/
   - Crie um projeto → Ative "YouTube Data API v3" → Credenciais → Criar chave de API
2. Instale as dependências:
      pip install google-api-python-client pandas tqdm
3. Execute:
      python raspar_youtube_cnh.py
4. O arquivo "comentarios_cnh.csv" será gerado na mesma pasta.

PARÂMETROS AJUSTÁVEIS (veja seção CONFIG abaixo):
- API_KEY              → sua chave da API
- MAX_VIDEOS           → quantos vídeos buscar por termo de pesquisa
- MAX_COMMENTS_PER_VIDEO → limite de comentários por vídeo
- ORDER                → "relevance" ou "time" (mais recentes)
"""

import os
import time
import csv
import re
from datetime import datetime
from tqdm import tqdm

try:
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
    import pandas as pd
except ImportError:
    print("Instale as dependências: pip install google-api-python-client pandas tqdm")
    raise

# ═══════════════════════════════════════════════════════════════
#  CONFIG — ajuste aqui
# ═══════════════════════════════════════════════════════════════
API_KEY = "AIzaSyDLtpTmA29SfNiQbjsXoO6FYP4y6OD8zWs"          # ← substitua pela sua chave

MAX_VIDEOS = 10                        # vídeos por termo de busca
MAX_COMMENTS_PER_VIDEO = 200          # comentários por vídeo (múltiplos de 100)
ORDER = "relevance"                    # "relevance" | "time"
OUTPUT_FILE = "comentarios_cnh.csv"

# Termos de busca relacionados às mudanças na CNH
TERMOS_BUSCA = [
    "novas regras CNH 2024 2025",
    "mudança processo tirar CNH Brasil",
    "CNH autoescola obrigatório mudança lei",
    "nova lei CNH habilitação Brasil",
    "processo CNH simplificado Brasil",
    "reforma CNH DENATRAN SENATRAN",
]
# ═══════════════════════════════════════════════════════════════


def criar_servico():
    return build("youtube", "v3", developerKey=API_KEY)


def buscar_videos(youtube, termo, max_results=10):
    """Busca vídeos no YouTube e retorna lista de dicts com metadados."""
    videos = []
    try:
        request = youtube.search().list(
            part="snippet",
            q=termo,
            type="video",
            maxResults=min(max_results, 50),
            relevanceLanguage="pt",
            regionCode="BR",
            order=ORDER,
            videoCaption="any",
        )
        response = request.execute()

        for item in response.get("items", []):
            vid_id = item["id"]["videoId"]
            snippet = item["snippet"]
            videos.append({
                "video_id": vid_id,
                "titulo": snippet.get("title", ""),
                "canal": snippet.get("channelTitle", ""),
                "canal_id": snippet.get("channelId", ""),
                "publicado_em": snippet.get("publishedAt", ""),
                "link": f"https://www.youtube.com/watch?v={vid_id}",
                "termo_busca": termo,
            })
    except HttpError as e:
        print(f"  [ERRO] Busca por '{termo}': {e}")
    return videos


def buscar_likes_video(youtube, video_id):
    """Retorna likes e views do vídeo."""
    try:
        resp = youtube.videos().list(
            part="statistics",
            id=video_id,
        ).execute()
        stats = resp["items"][0]["statistics"] if resp.get("items") else {}
        return {
            "video_likes": int(stats.get("likeCount", 0)),
            "video_views": int(stats.get("viewCount", 0)),
            "video_comentarios_total": int(stats.get("commentCount", 0)),
        }
    except Exception:
        return {"video_likes": None, "video_views": None, "video_comentarios_total": None}


def buscar_comentarios(youtube, video_id, max_comments=200):
    """
    Coleta comentários de um vídeo usando paginação.
    Retorna lista de dicts com dados de cada comentário.
    """
    comentarios = []
    page_token = None
    coletados = 0

    while coletados < max_comments:
        restante = max_comments - coletados
        page_size = min(restante, 100)

        try:
            params = dict(
                part="snippet",
                videoId=video_id,
                maxResults=page_size,
                textFormat="plainText",
                order=ORDER,
            )
            if page_token:
                params["pageToken"] = page_token

            resp = youtube.commentThreads().list(**params).execute()

            for item in resp.get("items", []):
                top = item["snippet"]["topLevelComment"]["snippet"]
                comentarios.append({
                    "comentario_id": item["id"],
                    "comentario": top.get("textDisplay", "").strip(),
                    "autor": top.get("authorDisplayName", ""),
                    "likes_comentario": int(top.get("likeCount", 0)),
                    "respostas": int(item["snippet"].get("totalReplyCount", 0)),
                    "data_comentario": top.get("publishedAt", ""),
                    "atualizado_em": top.get("updatedAt", ""),
                })
                coletados += 1

            page_token = resp.get("nextPageToken")
            if not page_token:
                break

            time.sleep(0.3)  # respeita rate limit

        except HttpError as e:
            codigo = e.resp.status
            if codigo == 403:
                print(f"  [AVISO] Comentários desativados no vídeo {video_id}.")
            elif codigo == 404:
                print(f"  [AVISO] Vídeo {video_id} não encontrado.")
            else:
                print(f"  [ERRO] {e}")
            break

    return comentarios


def limpar_texto(texto):
    """Remove emojis e caracteres de controle mantendo acentuação."""
    if not isinstance(texto, str):
        return ""
    # Remove caracteres de controle
    texto = re.sub(r"[\x00-\x1f\x7f]", " ", texto)
    # Remove emojis e símbolos (bloco Unicode acima de U+2600)
    texto = re.sub(r"[^\x00-\x7Fà-üÀ-Ü0-9\s\.,;:!?\"'()\-]", "", texto)
    return re.sub(r"\s+", " ", texto).strip()


def raspar(verbose=True):
    print("=" * 60)
    print("  Raspagem de Comentários YouTube — CNH Brasil")
    print(f"  Iniciado em: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print("=" * 60)

    if API_KEY == "SUA_API_KEY_AQUI":
        raise ValueError(
            "\n⚠️  Você precisa inserir sua API Key!\n"
            "   Edite a variável API_KEY no início do arquivo.\n"
            "   Obtenha gratuitamente em: https://console.cloud.google.com/"
        )

    youtube = criar_servico()

    # 1. Buscar vídeos — deduplicar por video_id
    print("\n📺 Buscando vídeos...")
    videos_map = {}
    for termo in TERMOS_BUSCA:
        print(f"  → '{termo}'")
        for v in buscar_videos(youtube, termo, MAX_VIDEOS):
            if v["video_id"] not in videos_map:
                videos_map[v["video_id"]] = v
        time.sleep(1)

    videos = list(videos_map.values())
    print(f"\n  ✅ {len(videos)} vídeos únicos encontrados.")

    # 2. Coletar comentários
    print(f"\n💬 Coletando comentários (até {MAX_COMMENTS_PER_VIDEO} por vídeo)...")
    registros = []

    for v in tqdm(videos, desc="Vídeos"):
        stats = buscar_likes_video(youtube, v["video_id"])
        comentarios = buscar_comentarios(youtube, v["video_id"], MAX_COMMENTS_PER_VIDEO)

        for c in comentarios:
            registros.append({
                # ── Vídeo ──────────────────────────────────────────
                "link_video":              v["link"],
                "titulo_video":            v["titulo"],
                "nome_canal":              v["canal"],
                "canal_id":                v["canal_id"],
                "video_publicado_em":      v["publicado_em"],
                "video_likes":             stats["video_likes"],
                "video_views":             stats["video_views"],
                "video_total_comentarios": stats["video_comentarios_total"],
                "termo_busca":             v["termo_busca"],
                # ── Comentário ─────────────────────────────────────
                "comentario_id":           c["comentario_id"],
                "comentario":              c["comentario"],
                "comentario_limpo":        limpar_texto(c["comentario"]),
                "autor":                   c["autor"],
                "likes_comentario":        c["likes_comentario"],
                "respostas":               c["respostas"],
                "data_comentario":         c["data_comentario"],
                "atualizado_em":           c["atualizado_em"],
                # ── Metadado ───────────────────────────────────────
                "raspado_em":              datetime.now().isoformat(),
            })

        time.sleep(0.5)

    # 3. Salvar CSV
    if not registros:
        print("\n⚠️  Nenhum comentário coletado. Verifique sua API Key e os termos de busca.")
        return

    df = pd.DataFrame(registros)

    # Remove duplicatas (mesmo comentário encontrado em buscas diferentes)
    antes = len(df)
    df = df.drop_duplicates(subset="comentario_id")
    print(f"\n  Duplicatas removidas: {antes - len(df)}")

    # Ordena por likes do comentário
    df = df.sort_values("likes_comentario", ascending=False).reset_index(drop=True)

    df.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig", quoting=csv.QUOTE_ALL)

    print(f"\n{'=' * 60}")
    print(f"  ✅ Raspagem concluída!")
    print(f"  📁 Arquivo: {OUTPUT_FILE}")
    print(f"  📊 Total de comentários únicos: {len(df)}")
    print(f"  🎥 Vídeos processados: {df['link_video'].nunique()}")
    print(f"  📺 Canais únicos: {df['nome_canal'].nunique()}")
    print(f"  👍 Comentário mais curtido: {df['likes_comentario'].max()} likes")
    print(f"  🕐 Finalizado em: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")
    print("=" * 60)

    return df


if __name__ == "__main__":
    raspar()